name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@2.0.1
        with:
          version: 6.13.0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.6.2'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test -- --coverage || exit 1